spring:
  datasource:
    url: jdbc:mysql://mysql-task:3306/task_serviceDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/



