spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/task_serviceDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password



