spring:
  datasource:
    url: jdbc:mysql://mysql-team:3306/team_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
