spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/team_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
