spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/project_ServiceDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
