spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/notification_servicedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password






