
spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true   # ðŸ”¥ VERY IMPORTANT
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH   # ðŸ”¥ REQUIRED
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - PreserveHostHeader         #for nignix add

        # âœ… SEPARATE WEBSOCKET ROUTE
        - id:  notification-ws
          uri: lb://notification-service   # or team-service (where socket lives) for nignix
          predicates:
            - Path=/ws/**
          filters:
            - PreserveHostHeader

        # Route for Task Service WebSockets
        - id:  task-ws
          uri: lb://task-service
          predicates:
            - Path=/ws/**
          filters:
            - PreserveHostHeader

#        # Route for Notification Service WebSockets
#        - id: notification-ws-route
#          uri: lb://notification-service
#          predicates:
#            - Path=/ws/notifications/**
#          filters:
#            - RewritePath=/ws/notifications/(?<segment>.*), /ws/$\{segment}

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/projects/**

#        - id: team-service
#          uri: lb://TEAMSERVICE
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/teams/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#       defaultZone: http://localhost:8761/eureka/
       defaultZone: http://eureka:8761/eureka




